version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "webserver"
    restart: unless-stopped
    ports:
      - "15000:8000"
    env_file: .env.prod
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=voidmon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery-worker"
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - ./db:/code/db
    depends_on:
      - redis
      - web
      - postgres
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery-beat"
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - ./db:/code/db
    depends_on:
      - redis
      - web
      - postgres
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
volumes:
  postgres_data:
