# Generated by Django 5.1.4 on 2025-01-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanissue",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("vulnerability", "Vulnerability"),
                ],
                default="info",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="scanissue",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "external_script_no_integrity_hash",
                        "External Script No Integrity Hash",
                    ),
                    (
                        "external_stylesheet_no_integrity_hash",
                        "External Stylesheet No Integrity Hash",
                    ),
                    (
                        "remote_resource_loaded_over_http",
                        "Remote Resource Loaded Over HTTP",
                    ),
                    ("non_html_response", "Non HTML Response"),
                ],
                max_length=255,
            ),
        ),
    ]
