# Generated by Django 5.1.4 on 2025-01-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_scanissue_severity_alter_scan_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="scan",
            name="url",
            field=models.URLField(max_length=1024),
        ),
    ]
