# Generated by Django 5.1.5 on 2025-02-09 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_scan_finished_at_scan_started_at_alter_scan_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsubscription",
            name="url",
            field=models.URLField(max_length=1024),
        ),
        migrations.CreateModel(
            name="DynamicScanResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dom_content_loaded_after", models.IntegerField()),
                ("load_after", models.IntegerField()),
                ("network_idle_after", models.IntegerField()),
                ("num_requests", models.IntegerField()),
                ("size", models.IntegerField()),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.scan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicScanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(max_length=1024)),
                ("method", models.CharField()),
                ("resource_type", models.CharField()),
                ("status", models.IntegerField(null=True)),
                ("error", models.CharField(null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "dynamic_scan_results",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_set",
                        to="core.dynamicscanresults",
                    ),
                ),
            ],
        ),
    ]
