# Generated by Django 5.1.5 on 2025-02-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_notificationsubscription_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
