# Generated by Django 5.1.5 on 2025-02-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_scan_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicscanrequest",
            name="url",
            field=models.URLField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="notificationsubscription",
            name="url",
            field=models.URLField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="scan",
            name="url",
            field=models.URLField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="scanissue",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "external_script_no_integrity_hash",
                        "External Script No Integrity Hash",
                    ),
                    (
                        "external_stylesheet_no_integrity_hash",
                        "External Stylesheet No Integrity Hash",
                    ),
                    (
                        "remote_resource_loaded_over_http",
                        "Remote Resource Loaded Over HTTP",
                    ),
                    ("non_html_response", "Non HTML Response"),
                    ("external_script_dns_failure", "External Script DNS Failure"),
                    (
                        "external_stylesheet_dns_failure",
                        "External Stylesheet DNS Failure",
                    ),
                    (
                        "external_script_address_unreachable",
                        "External Script Address Unreachable",
                    ),
                    (
                        "external_stylesheet_address_unreachable",
                        "External Stylesheet Address Unreachable",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
