from .enums import ScanIssueSeverity, ScanIssueType

SCAN_ISSUE_TYPE_TO_SEVERITY = {
    ScanIssueType.EXTERNAL_SCRIPT_NO_INTEGRITY_HASH: ScanIssueSeverity.WARNING,
    ScanIssueType.EXTERNAL_SCRIPT_DNS_FAILURE: ScanIssueSeverity.VULNERABILITY,
    ScanIssueType.EXTERNAL_SCRIPT_ADDRESS_UNREACHABLE: ScanIssueSeverity.VULNERABILITY,
    ScanIssueType.EXTERNAL_STYLESHEET_NO_INTEGRITY_HASH: ScanIssueSeverity.WARNING,
    ScanIssueType.EXTERNAL_STYLESHEET_DNS_FAILURE: ScanIssueSeverity.VULNERABILITY,
    ScanIssueType.EXTERNAL_STYLESHEET_ADDRESS_UNREACHABLE: ScanIssueSeverity.VULNERABILITY,
    ScanIssueType.REMOTE_RESOURCE_LOADED_OVER_HTTP: ScanIssueSeverity.VULNERABILITY,
    ScanIssueType.NON_HTML_RESPONSE: ScanIssueSeverity.VULNERABILITY,
}

SCAN_ISSUE_TYPE_TO_DEFAULT_MESSAGE = {
    ScanIssueType.NON_HTML_RESPONSE: "URL did not return HTML content",
}
